### ISSUE TITLE
Add ICCV 2023 paper: Generative Prompt Model for Weakly Supervised Object Localization

### ISSUE THREAD

**Issue by callsys** [Sierkinhane/ICCV2023-Diffusion-Papers#3]
Paper name: Generative Prompt Model for Weakly Supervised Object Localization
Paper link: https://arxiv.org/abs/2307.09756
Code link: https://github.com/callsys/GenPromp
Related area: Diffusion
Thank you!

**Comment by Sierkinhane** [comment]
Got it!
