### ISSUE TITLE
Add paper

### ISSUE THREAD

**Issue by FutureXiang** [Sierkinhane/ICCV2023-Diffusion-Papers#7]
Paper name: Denoising Diffusion Autoencoders are Unified Self-supervised Learners
Paper link: https://arxiv.org/abs/2303.09769
Code link: https://github.com/FutureXiang/ddae

Selected for *Oral* presentation at ICCV 23.
Related area: Diffusion, Self-supervised representation learning

Thank you!

**Comment by Sierkinhane** [comment]
Thank you for sharing. I have included the paper in the repository.
